### ISSUE TITLE
V12 project_wbs module 

### ISSUE THREAD

**Issue by CasVissers-360ERP** [Eficent/eficent-odoo-addons#123]
Hi,

I'm taking a look at your big set of analytic modules which we might want to use and contribute on.

In my research thus far I can't seem to find the project_wbs module for v12. Although dependency modules like analytic_plan are ported.

Is the project_wbs available, I can't seem to find any version newer then v10.

Thank you for your time,
Cas

**Comment by AaronHForgeFlow** [comment]
Hi @CasVissers I love you are interested in those modules.

project_wbs is a PR to OCA at this moment: https://github.com/OCA/project/pull/471

All contributions are welcome :smile: 

Regards

**Comment by CasVissers-360ERP** [comment]
Thnx!

**Comment by CasVissers-360ERP** [comment]
@aheficent 
Hopefully I can misuse this issue for a question.

I have your WiP modules running in v12, when I get a signature for the project I will make sure we will make PR"s for all related unported modules. 

I have everything running and it looks great, only thing I can't get my head around is labor costs. 

`                SELECT amount, L.id, AAJ.cost_type
                       FROM account_analytic_line L
                       INNER JOIN account_analytic_journal AAJ
                       ON AAJ.id = L.journal_id
                       INNER JOIN account_account AC
                       ON L.general_account_id = AC.id
                       INNER JOIN account_account_type AT
                       ON AT.id = AC.user_type_id
                       WHERE AT.name in ('Expenses', 'Cost of Revenue')
                       AND L.account_id IN %s`
First the costs are calculated and then split per cost_type. The problem I have is that the timesheet entries are not found in this calculation since they don't have an account set. 

How did you guys solve this?

Thank you for your time.
Cas

**Comment by AaronHForgeFlow** [comment]
That is great news! :smiley:  I hope everything goes well

We have some customizations for that. Basically it uses the information in the payslips to update the analytic lines. But it is very customized for the customer. That is why we did not put it in this repo. Perhaps there is a more generic solution, the problem is users can change timesheets all the time, and depending on the project and the employee we may have different accounts.

Regards.

**Comment by CasVissers-360ERP** [comment]
Fyi, we are currently working on:

- analytic_cost_revenue
- analytic_journal
- analytic_plan
- analytic_plan_cost_revenue
- analytic_wip_report
- project_wbs
- project_wbs_stage

Some of them we take from OCA, we are also working on a timesheet journal entry module based on OCA timesheet sheet module.
