### ISSUE TITLE
[odoo 9.0] mrp_production_merge_component

### ISSUE THREAD

**Issue by alaa9jo** [Eficent/eficent-odoo-addons#17]
Are there any plans for mrp_production_merge_component to support odoo 9.0 ? I've searched everywhere for a way to merge manufacturing orders into one order and it seems this is one of the most promising modules for that.

**Comment by JordiBForgeFlow** [comment]
@alaa9jo This module does not do what you seem to expect. If a production order contains multiple lines of the same product, these lines are merged into a single line. This is useful for multi-level BOM's that refer to the same product multiple times.

**Comment by alaa9jo** [comment]
@jbeficent I get it now, thanks!
