### ISSUE TITLE
account_move_budget VS analytic_plan

### ISSUE THREAD

**Issue by kittiu** [Eficent/eficent-odoo-addons#214]
@ForgeFlow @JordiBForgeFlow 

`account.analytic.line.plan` remind me about account_move_budget that you did in order to use mis_builder.
https://github.com/OCA/account-financial-tools/pull/789

Now, I see `account.analytic.line.plan`, the concept looks similar. I am curious why you don't just use `account.analytic.line.plan` for `account.move.budget.line`?
Only if account.analytic.line.plan has debit / credit field, it could be used in mis_builder already, isn't it?

I do not propose any thing here. Just that, I was doing budget control modules, and I did create new model `xxx.budget.move` 
https://github.com/ecosoft-odoo/account-budgeting/blob/12.0-add-budget_control/budget_control/models/base_budget_move.py

When I see your `account.analytic.line.plan` I think I might be able to reuse it. I don't want to reinventing things if not necessary. You might have good reasons.

Thanks

**Comment by AaronHForgeFlow** [comment]
This is interesting. I am not too familiar with account_budget, but at first sight the concept looks similar to budget lines. Analytic plan was created specifically for projects though. 

Analytic plan is not a new concept in Odoo, it was created a long time ago (Openerp 7) and there are now various  applications that run on top of that, like project bids, resource plan, work in progress statement.... refactoring that is not an easy task so IMO very powerful reason would be required to Refactor Analytic plan module. 

But as I said, I am not too familiar with budgets so I need to review them first.

Thanks you!

**Comment by kittiu** [comment]
Thank you Aaron for your comments :)

**Comment by AaronHForgeFlow** [comment]
Thanks to you! :)
