### ISSUE TITLE
[7.0] [analytic_wip_report_fiscalyear] - Add extra filters by start and end date within fiscal year selected

### ISSUE THREAD

**Issue by JordiBForgeFlow** [Eficent/eficent-odoo-addons#24]
The current module "analytic_wip_report_fiscalyear" just filters by the start and end date of the fiscal year that the user selected in the wizard.

But sometimes you want to run the report for some start and end date within that year (for example, 1st quarter).

When the user enters the fiscal year, a separate date from/to should appear, defaulting with the fiscal year's default start and end date. The user should be able to change the dates. These should be the dates that should be considered to run the report.

Once the user executes the report, the application should validate that the dates that were entered fall within the fiscal year's start and end dates.

**Comment by AaronHForgeFlow** [comment]
Solved.
