### ISSUE TITLE
migration in version 10

### ISSUE THREAD

**Issue by ccandito** [Eficent/eficent-odoo-addons#81]
Dear All,
please I need to specify an analytic account at location level.
I did it in version 9.
Could you please tell me about the differences between 
stock_analytic_account_location	
stock_location_analytic
and when these modules will be imported in version 10.
Regards
claudio candito

**Comment by AaronHForgeFlow** [comment]
Closing as answered out of github. Copying the answer here:

- stock_analytic_location: Introduces the analytic account to the locations. It's a base module to assign the analytic account to a location and add some constraints.
- stock_analytic_account_location: It depends on stock_analytic_location. It Assigns the analytic account to the stock move only when we are moving items to a location that is assigned to an analytic account. This location could be out of the company (defining some locations of type 'customer'). This could be useful for recognizing  expensea for a project. The system will recognize the expense for an analytic account when we move from an internal location to out of the company.
